### ISSUE TITLE
Error in Ubuntu 14.04 when npm install cloudcv-bootstrap

### ISSUE THREAD

**Issue by rcmalli** [CloudCV/cloudcv-bootstrap#1]
multiple of warnings 

![screenshot](https://cloud.githubusercontent.com/assets/7341604/7539133/70a6a9e2-f5ad-11e4-9452-ac024863941a.png)

one error

![screenshot](https://cloud.githubusercontent.com/assets/7341604/7539155/8f83d074-f5ad-11e4-928f-2ebfccbdad5d.png)

**Comment by BloodAxe** [comment]
Which version of node are you using? It seems your version of V8 that ships with node does not have `HasTerminated()` method for `v8::TryCatch`.

**Comment by rcmalli** [comment]
Default Ubuntu package manager has node version 0.10.x . I installed new version ( v0.12.2 ) with nvm tool and now it builds correctly
