### ISSUE TITLE
Problems with CORS

### ISSUE THREAD

**Issue by MHerszak** [CloudCV/cloudcv-bootstrap#2]
Hi,
I am experiencing problems with Cross-Origin Request Blocked. I am getting the following error from the console.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://45.55.223.62:3000/api/v1/image/analyze/dominantColors/?image=http%3A%2F%2F45.55.223.62%3A8888%2Fimages%2Fmandrill.png. This can be fixed by moving the resource to the same domain or enabling CORS.

My header response is:
Connection: keep-alive
Content-Type: application/json
Date: Thu, 14 May 2015 06:04:28 GMT
Transfer-Encoding: chunked
X-Powered-By: Express

Any idea what that could be?
Cheers,
Michel

**Comment by BloodAxe** [comment]
Cors is enabled. Sorry for late reply but it has been fixed a long time ago
