### ISSUE TITLE
Independent NanCheck

### ISSUE THREAD

**Issue by JCMais** [CloudCV/cloudcv-bootstrap#4]
Would it be possible to create a new project just for NanCheck?

I think it would be really interesting for people building node.js addons.

**Comment by BloodAxe** [comment]
It's a probably a good idea. There will be a nan-check module providing Nan::Check methods.

**Comment by BloodAxe** [comment]
@JCMais update module will be placed here: https://github.com/BloodAxe/nan-check

**Comment by JCMais** [comment]
Nice! Thank you @BloodAxe for taking the time to do that!

**Comment by BloodAxe** [comment]
Done! Check https://github.com/BloodAxe/nan-marshal & https://github.com/BloodAxe/nan-check.
