### ISSUE TITLE
Interactive Background removal

### ISSUE THREAD

**Issue by pulankit** [CloudCV/cloudcv-bootstrap#5]
Hey currently i am working on a background removal feature i have already implemented in opencv using grabcut but for the web thing i wonder  how could i use your cloud cv to integrate opencv libraries ?? Reply Asap!!nks
Thanks!

**Comment by ekhvedchenya-daqri** [comment]
1) Fork this project
2) Add your bindings using https://github.com/CloudCV/cloudcv-bootstrap/blob/master/src/modules/analyze/AnalyzeImageBinding.cpp as example. Don't forget to add new files in binding.gyp.
3) Compile module and write some tests to ensure it's working as expected. See https://github.com/CloudCV/cloudcv-bootstrap/tree/master/test.
4) Expose REST API endpoint by adding new handler in server.js as follows:
app.post('/api/v1/image/grabCut/', function (req, res) { .. })
5) (Optional) Remove front-end part if you don't need it.

**Comment by BloodAxe** [comment]
1) Fork this project
2) Add your bindings using https://github.com/CloudCV/cloudcv-bootstrap/blob/master/src/modules/analyze/AnalyzeImageBinding.cpp as example. Don't forget to add new files in binding.gyp.
3) Compile module and write some tests to ensure it's working as expected. See https://github.com/CloudCV/cloudcv-bootstrap/tree/master/test.
4) Expose REST API endpoint by adding new handler in server.js as follows:
app.post('/api/v1/image/grabCut/', function (req, res) { .. })
5) (Optional) Remove front-end part if you don't need it.

**Comment by pulankit** [comment]
i didn't get you, point 2 is not clear i tried to go through the code but i didn't grab that i  don't have any ideas about writing node ad-dons and also about v8 could you be more descriptive..Would be highly great full to you

**Comment by BloodAxe** [comment]
Detailed instructions will be added someday. But now the best way to start is copy AnalyzeImageBinding.cpp
AnalyzeImageBinding.cpp to new file (let's call it GrabCutBinding.cpp) and start modifying it to fit your needs. Also, edit binding.gyp file and add newly created file near to AnalyzeImageBinding.cpp. 
If you want to expose your algorithm you will have to learn new things. So I encourage you to read https://nodejs.org/docs/latest/api/addons.html to get some insights on what native modules for nodejs are.

**Comment by pulankit** [comment]
ohk thanks for tha advice but i am already trying on that but having real
hard time.. could you like give me code of your original AnalyzeImage algo
written in core c++ so that i can actually compare and annalyse how to go
about writing the same stuff for my code,

**Comment by pulankit** [comment]
ohk found the code! ..
