### ISSUE TITLE
Suggestion for increased usage of this concept using API client/server generators

### ISSUE THREAD

**Issue by mcanthony** [CloudCV/cloudcv-bootstrap#6]
I was thinking after finding this project that it is a great idea, and wondered if you thought it might be a good idea to write a Swagger spec for the API, so that you could from automatically generate a variety of different types of servers and clients for a large number of available programming languages. I am not 100% sure what would be involved in the process of generating bindings for OpenCV for each language, but I do know many different bindings exist that could be adapted for this purpose.

This would make the project interesting for a wider audience. If you feel this is worth investigating further I will start doing some research and see what all would be necessary. I am fairly new to Swagger and OpenCV, but I learn quick.

**Comment by BloodAxe** [comment]
Hi! Currenty i'm working on automatic generation of REST API specifications in [expose-algorithm-params](https://github.com/CloudCV/cloudcv-bootstrap/tree/expose-algorithm-params) branch. This requires slight change of paradigm we write bindings, but it should expose all expected input/output data formats, that we later elaborate to generate Swagger specs.
