### ISSUE TITLE
Build Error: No Matching Function for Call to v8::Signature ::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)

### ISSUE THREAD

**Issue by krishna95** [CloudCV/cloudcv-bootstrap#7]
Hi All,

I am very much new to nodejs and npm and  want to make a webapp for an image processing algorithm. For the same, I want to use this template of cloudcv-bootstrap and hence, I carried the install procedure as was mentioned. My verisons are as follows:

node -- 4.2.3
npm -- 2.14.7
nodejs -- 0.10.25

When I ran npm install, it starts building after installing all the dependencies. However, I got the following errors:

make: Entering directory `/home/kinoder/ws/cloudcv-bootstrap/build'
  CXX(target) Release/obj.target/cloudcv/src/cloudcv.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../src/cloudcv.cpp:14:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBasev8::Signature::return_t NanIntern::Factoryv8::Signature::New(NanIntern::Factoryv8::Signature::FTH, int, NanIntern::Factoryv8::Signature::FTH_)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate_, NanIntern::Factoryv8::Signature::FTH&, int&, NanIntern::Factoryv8::Signature::FTH_&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /home/kinoder/.node-gyp/4.2.3/include/node/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/cloudcv.cpp:14:
/home/kinoder/.node-gyp/4.2.3/include/node/v8.h:4675:27: note: static v8::Localv8::Signature v8::Signature::New(v8::Isolate_, v8::Localv8::FunctionTemplate)
   static Local<Signature> New(
                           ^
/home/kinoder/.node-gyp/4.2.3/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/cloudcv.cpp:14:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:171:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:166:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:564:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:564:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(char_, size_t, int)’:
../node_modules/nan/nan.h:568:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:568:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(const char_, uint32_t)’:
../node_modules/nan/nan.h:575:67: error: call of overloaded ‘New(v8::Isolate_, const char_&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:575:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/cloudcv.cpp:14:
/home/kinoder/.node-gyp/4.2.3/include/node/node_buffer.h:31:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, v8::Localv8::String, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/kinoder/.node-gyp/4.2.3/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/kinoder/.node-gyp/4.2.3/include/node/node_buffer.h:43:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
/home/kinoder/.node-gyp/4.2.3/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char_’ to ‘char_’
In file included from ../src/cloudcv.cpp:14:0:
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:579:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocalv8::Object’ to ‘v8::Localv8::Object’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Localv8::Object NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:586:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
Is there anything that I can do to resolve this issue ?

**Comment by BloodAxe** [comment]
Your version of nodejs is very old. This project aims nodejs 0.12 and
higher.

2015-12-04 20:48 GMT+02:00 krishna95 notifications@github.com:
