### ISSUE TITLE
Incorrect display in we browser.

### ISSUE THREAD

**Issue by satishlokkoju** [CloudCV/cloudcv-bootstrap#8]
Hi,
Thank you for cloudcv-bootstrap. 
I am unable to generate the sample output (dominant colors palette display) on a web broswer
Wondering if the latest release broke some code?

Also, using curl localhost:3000/api/v1/image/analyze/dominantColors?image=opencv-logo.jpg   is returning json formatted dominant color output as explained.

-Satish.

**Comment by BloodAxe** [comment]
That's right, latest update shifted aim to REST-API. There will be JavaScript SDK around this API, but the front-end will be solely in your responsibility. You get the data and it's up to you how to utilize it.
